 id |                                                                            text                                                                             |                                                  image                                                   |   position   | set_lesson_id |             title
----+-------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+--------------+---------------+-------------------------------
 23 | Hiragana is the Japanese alphabet, so it's the first thing you should learn when you're learning Japanese.                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-a/lecture-1.png   | PRETEST      | HIRAGANA_A    | What is Hiragana?
 24 | Hiragana each represent syllables, rather than single letters.                                                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-a/lecture-2.png   | PRETEST      | HIRAGANA_A    | What is Hiragana?
 25 | Because they represent syllables, they are always pronounced exactly the same way, unlike English letters.                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-a/lecture-2.png   | PRETEST      | HIRAGANA_A    | What is Hiragana?
 26 | Hiragana come in sets of 5. In this lesson, we'll learn the first 5 - A, I, U, E, and O.                                                                    | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-a/lecture-4.png   | PRETEST      | HIRAGANA_A    | What is Hiragana?
 27 | Now that we've covered the hiragana with no consonants, the rest of them will have a consonant sound.                                                       | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ka/lecture-1.png  | PRETEST      | HIRAGANA_KA   | The Next Set
 28 | This next set is the "ka" set, which all start with K (and, of course, end in A, I, U, E, and O)                                                            | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ka/lecture-2.png  | PRETEST      | HIRAGANA_KA   | The Next Set
 35 | The next set of hiragana is the "sa" set. They all start with an "s" sound.                                                                                 | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-sa/lecture-1.png  | PRETEST      | HIRAGANA_SA   | The Sa Set
 36 | Well... that's not entirely true. Instead of "si", it's "shi".                                                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-sa/lecture-2.png  | PRETEST      | HIRAGANA_SA   | The Sa Set
 37 | After all, we couldn't have sushi without the "shi" sound!                                                                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-sa/lecture-3.png  | PRETEST      | HIRAGANA_SA   | The Sa Set
 38 | A voiced consonant is a consonant that you need to move your vocal cords to make.                                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-1.png  | PRETEST      | HIRAGANA_GA   | What is a "voiced" consonant?
 39 | For example, K is unvoiced, and G is voiced. G is actually the same as K, with vocal cords added.                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-2.png  | PRETEST      | HIRAGANA_GA   | What is a "voiced" consonant?
 40 | You can try it yourself! Put your hand on your throat and make K and G sounds.                                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-3.png  | PRETEST      | HIRAGANA_GA   | What is a "voiced" consonant?
 41 | In Japanese, you can make a hiragana's consonant part voiced by adding a TenTen                                                                             | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-4.png  | PRETEST      | HIRAGANA_GA   | The TenTen
 42 | In this lesson, we'll learn words with the "ga" set. That's the "ka" set plus TenTens.                                                                      | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-5.png  | PRETEST      | HIRAGANA_GA   | The TenTen
 43 | Remember, TenTens can be added to hiragana to make the consonant part "voiced".                                                                             | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-za/lecture-1.png  | PRETEST      | HIRAGANA_ZA   | The Za Set
 44 | The "sa" set can also have a TenTen attached, which turns an S sound into a Z sound.                                                                        | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-za/lecture-2.png  | PRETEST      | HIRAGANA_ZA   | The Za Set
 45 | The one exception, of course, is "し" (shi). Shi becomes *ji*. Let's get started!                                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-za/lecture-3.png  | PRETEST      | HIRAGANA_ZA   | The Za Set
 46 | Sorry, just one more thing. This little character "っ" doubles consonant sounds.                                                                            | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-za/lecture-4.png  | BEFORE_THIRD | HIRAGANA_ZA   | The Consonant Doubler
 47 | It doesn't make any sound on its own, but it extends the consonant sound of the next hiragana.                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-za/lecture-5.png  | BEFORE_THIRD | HIRAGANA_ZA   | The Consonant Doubler
 48 | It's hard to explain it fully here. All you need to know is that to write it, you write a second consonant.                                                 | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-6.png  | BEFORE_THIRD | HIRAGANA_ZA   | The Consonant Doubler
 49 | If you'd like to know more, it might be worth checking out some YouTube videos that explain it.                                                             | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ga/lecture-7.png  | BEFORE_THIRD | HIRAGANA_ZA   | The Consonant Doubler
 50 | The fourth set of hiragana is the "ta" set, which is the trickiest set of all.                                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ta/lecture-1.png  | PRETEST      | HIRAGANA_TA   | The Ta Set
 51 | Instead of "ti" it's "chi", and instead of "tu" it's "tsu"                                                                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ta/lecture-2.png  | PRETEST      | HIRAGANA_TA   | The Ta Set
 52 | That's right, this character "つ" is "tsu". When it's small, it doubles consonants, but full sized it's a letter on its own                                 | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ta/lecture-3.png  | PRETEST      | HIRAGANA_TA   | Tsu?
 53 | Here they are side by side, so you can see the difference: "つっ".                                                                                          | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ta/lecture-4.png  | PRETEST      | HIRAGANA_TA   | Tsu?
 54 | The "ta" set is the second last set that can have TenTens added, but it's a bit different because of "chi" and "tsu".                                       | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-da/lecture-1.png  | PRETEST      | HIRAGANA_DA   | Ta Set + TenTens
 55 | The T sound in the normal ones ("ta", "te" and "to") becomes a D sound.                                                                                     | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-da/lecture-2.png  | PRETEST      | HIRAGANA_DA   | Ta Set + TenTens
 56 | "chi" and "tsu" technically can have TenTens, but it's quite rare to see them. (They become second versions of "ji" and "zu")                               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-da/lecture-3.png  | PRETEST      | HIRAGANA_DA   | Ta Set + TenTens
 57 | For now, you can safely assume that they never get TenTens, so there's only 3 new characters in this lesson!                                                | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-da/lecture-4.png  | PRETEST      | HIRAGANA_DA   | Ta Set + TenTens
 58 | There aren't any strange exceptions or new rules in the "na" set! Enjoy the lesson.                                                                         | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-na/lecture-1.png  | PRETEST      | HIRAGANA_NA   | The Na Set
 59 | "n" is already a voiced consonant, so letters in the "na" line cannot have a TenTen. This bonus round is different.                                         | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-n/lecture-1.png   | PRETEST      | HIRAGANA_N    | The Na Set Bonus Round
 60 | In this lesson, you'll learn a new letter, "ん" "n". This is a special letter: It's the only Japanese letter that represents a single consonant, by itself. | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-n/lecture-2.png   | PRETEST      | HIRAGANA_N    | The Letter N
 61 | Since it's only one new letter, we'll cover three new, useful words which use it.                                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-n/lecture-3.png   | PRETEST      | HIRAGANA_N    | The Letter N
 66 | The sixth hiragana set is the "ha" set. It only has one tricky character.                                                                                   | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ha/lecture-1.png  | PRETEST      | HIRAGANA_HA   | The Ha Set
 67 | The tricky one is written as "fu", but it's pronounced more like "fhu". It's a combination of the H and F sounds.                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ha/lecture-2.png  | PRETEST      | HIRAGANA_HA   | Fu? Hu? Fhu?
 68 | The "ha" set is the last set that can have TenTens attached. When it does, it transforms the sound from "H" to "B".                                         | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ba/lecture-1.png  | PRETEST      | HIRAGANA_BA   | Back to TenTens
 69 | Even though "ふ" is an exception, it gets changed to "bu", just like the rest of the set.                                                                   | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ba/lecture-2.png  | PRETEST      | HIRAGANA_BA   | What About Fu?
 70 | The seventh set of hiragana is the "ma" set. Only 3 more to go!                                                                                             | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ma/lecture-1.png  | PRETEST      | HIRAGANA_MA   | The Ma Set
 71 | Just like the "な" set, it doesn't have any tricky characters. Enjoy!                                                                                       | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ma/lecture-2.png  | PRETEST      | HIRAGANA_MA   | The Ma Set
 72 | This bonus round is all about the "wa" set, although it's not much of a set.                                                                                | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-wa/lecture-1.png  | PRETEST      | HIRAGANA_WA   | The Wa "Set"
 73 | There are only "two" characters in the set, and one of them isn't even used in words (it's more like a punctuation mark).                                   | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-wa/lecture-2.png  | PRETEST      | HIRAGANA_WA   | The Wa Set
 74 | There's "wa", which is the real character, and "wo", which is the weird, semi-fake character.                                                               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-wa/lecture-3.png  | PRETEST      | HIRAGANA_WA   | The Wa Set
 75 | It doesn't make much sense now, but once you start learning how to make Japanese sentences, "wo" will become very important!                                | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-wa/lecture-4.png  | PRETEST      | HIRAGANA_WA   | The Wa Set
 76 | We're getting to the end of the hiragana sets, and they do get a bit strange from here on.                                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ya/lecture-1.png  | PRETEST      | HIRAGANA_YA   | The Ya Set
 77 | This set is the "ya" set, but it looks like it's missing two characters.                                                                                    | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ya/lecture-2.png  | PRETEST      | HIRAGANA_YA   | The Ya Set
 78 | Japanese doesn't actually have the yi and ye sounds. There are only three characters in this set.                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ya/lecture-3.png  | PRETEST      | HIRAGANA_YA   | The Ya Set
 79 | Just like "つ", "ya", "yu" and "yo" can also become smaller to do something different.                                                                      | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-lya/lecture-1.png | PRETEST      | HIRAGANA_LYA  | Little Ya, Yu, and Yo
 80 | They can go after any hiragana that ends in "i" ("shi", "chi", "hi", "ni", etc.) to modify the sound.                                                       | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-lya/lecture-2.png | PRETEST      | HIRAGANA_LYA  | Little Ya, Yu and Yo
 81 | For example, "ki" + "ya" = "kya". There are lots of combinations, so they're not all listed here.                                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-lya/lecture-3.png | PRETEST      | HIRAGANA_LYA  | Little Ya, Yu and Yo
 82 | Once you get the hang of how they combine, it will feel pretty intuitive!                                                                                   | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-lya/lecture-4.png | PRETEST      | HIRAGANA_LYA  | Little Ya, Yu and Yo
 83 | This is the final set of hiragana! Well done for making it all the way here.                                                                                | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ra/lecture-1.png  | PRETEST      | HIRAGANA_RA   | The Ra Set
 84 | The "ra" set is hard for English speakers to pronounce, in the same way the English "l" and "r" are hard for Japanese people                                | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ra/lecture-2.png  | PRETEST      | HIRAGANA_RA   | The Ra Set
 85 | It's definitely worth checking out some videos to practice your pronunciation.                                                                              | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ra/lecture-3.png  | PRETEST      | HIRAGANA_RA   | The Ra Set
 86 | Other than that, this set is pretty normal. Just one more bonus lesson after this!                                                                          | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-ra/lecture-4.png  | PRETEST      | HIRAGANA_RA   | The Ra Set
 87 | The "は" set has one last trick up its sleeve, besides the TenTen.                                                                                          | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-pa/lecture-1.png  | PRETEST      | HIRAGANA_PA   | Return To The Ha Set
 88 | The Maru is sort of like the TenTen - it changes how hiragana is pronounced, but it only works with the "は" set.                                           | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-pa/lecture-2.png  | PRETEST      | HIRAGANA_PA   | The Maru
 89 | When a hiragana from the "は" set has a Maru, its consonant sound changes from "H" to "P".                                                                  | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262011/lessons/hiragana-pa/lecture-3.png  | PRETEST      | HIRAGANA_PA   | The Maru