 id |  japanese  |   hiragana   |               english               |                                                                      introduction                                                                      | emoji | image | set_lesson_id
  1 | 青         | あお         | Blue                                | This word means "blue". The first letter is "a" and the second letter is "o". Make sure you listen to the pronunciation!                               | 🔵     |       | HIRAGANA_A
  2 | 家         | いえ         | House                               | This is "house". The first letter is "i" and the second letter is "e".                                                                                 | 🏠     |       | HIRAGANA_A
  3 | いいえ     | いいえ       | No                                  | This word means "no". It's very similar to "house" isn't it? The only difference is you say "ii" for longer.                                           | 🙅<U+200D>♀️   |       | HIRAGANA_A
  4 | 上         | うえ         | Up                                  | This word means "up". The first letter is "u". You should already know the second letter!                                                              | ⬆️    |       | HIRAGANA_A
  5 | 赤         | あか         | Red                                 | This word means "red". The new letter is "ka".                                                                                                         | 🔴     |       | HIRAGANA_KA
  6 | 駅         | えき         | Train station                       | This word means "train station". The new letter is "ki".                                                                                               | 🚉     |       | HIRAGANA_KA
  7 | 空港       | くうこう     | Airport                             | This word means "airport". く is read as "ku" and こ is read as "ko".                                                                                  | 🛫     |       | HIRAGANA_KA
  8 | 計画       | けいかく     | Plan                                | This word means "plan" or "scheme". け is read as "ke". Just according to keikaku!                                                                     | 📑     |       | HIRAGANA_KA
  9 | 映画       | えいが       | Movie                               | This is "movie". Remember to watch out for the little tenten! It turns K -> G                                                                          | 🎬     |       | HIRAGANA_GA
 10 | 鍵         | かぎ         | Key                                 | This is "key". Some homework: Try to say it in your head whenever you pick up your own keys!                                                           | 🔑     |       | HIRAGANA_GA
 11 | 英語       | えいご       | English (language)                  | This word means "English", as in the language. You'll probably use it a lot in conversation.                                                           | 🇬🇧    |       | HIRAGANA_GA
 12 | 影         | かげ         | Shadow                              | Shadow. Not the most useful word, but easy to remember: "かげ bunshin no jutsu!"                                                                       | 👤     |       | HIRAGANA_GA
 13 | 家具       | かぐ         | Furniture                           | This word means "furniture". Another good one to say in your head whenever you use furniture!                                                          | 🛋     |       | HIRAGANA_GA
 14 | 遅い       | おそい       | Slow, late                          | This word means "slow" or "late". そ is pronounced as "so".                                                                                            | ⌛🐌️   |       | HIRAGANA_SA
 15 | 酒         | さけ         | Sake                                | This word is so common it's almost English! In Japanese, "sake" can mean rice wine, or just alcohol in general. It's "sah-keh" not "saa-kee"!          | 🍶     |       | HIRAGANA_SA
 16 | 寿司       | すし         | Sushi                               | You know this word already too! Remember to follow Japanese pronunciation: "su-shi" not "soo-shi".                                                     | 🍣     |       | HIRAGANA_SA
 17 | 学生       | がくせい     | School student                      | This is "school student". The new letter is "se".                                                                                                      | 👩<U+200D>🎓    |       | HIRAGANA_SA
 18 | 凄い       | すごい       | Amazing                             | This is one of the most common words in Japanese. Sugoi! Amazing!                                                                                      | 🤩     |       | HIRAGANA_SA
 19 | 風邪       | かぜ         | Cold, flu                           | This word means "cold" or "flu". Watch for those tenten marks! S -> Z.                                                                                 | 🤒     |       | HIRAGANA_ZA
 20 | 像         | ぞう         | Elephant                            | This word means "elephant".                                                                                                                            | 🐘     |       | HIRAGANA_ZA
 21 | 雑誌       | ざっし       | Magazine                            | This is "magazine". Remember, the little っ makes a longer consonant sound for the character that follows it.                                          | 🗞     |       | HIRAGANA_ZA
 22 | 静か       | しずか       | Quiet                               | This means "quiet". You might see this on signs in Japanese accomodation.                                                                              | 🤫     |       | HIRAGANA_ZA
 23 | 味         | あじ         | Flavour                             | This means flavour, you see it on Japanese snacks a lot. Remember, し is different. Instead of becoming "zi", it becomes "ji".                         | 😋     |       | HIRAGANA_ZA
 24 | 高い       | たかい       | High, expensive                     | This means "small". Remember, this new letter is an exception - it's "chi", not ti.                                                                    | 🏔     |       | HIRAGANA_TA
 25 | 小さい     | ちいさい     | Small                               | This means "small". This line of hiragana has some weird ones, like how the さ line had "shi" instead of "si". This new letter isn't "ti", it's "chi". | 🐜     |       | HIRAGANA_TA
 26 | 次         | つぎ         | Next                                | This word means "next". It's on some of the buttons in this very app!                                                                                  | ⏭     |       | HIRAGANA_TA
 27 | 年         | とし         | Year                                | This is "year". You'll see its kanji quite often in dates: 年. The first letter is と.                                                                 | 🗓     |       | HIRAGANA_TA
 28 | 手         | て           | Hand                                | Some letters are words just by themselves. This is "te": "hand".                                                                                       | ✋     |       | HIRAGANA_TA
 29 | 大学       | だいがく     | University, college                 | This word is university. I'm sure you've got the hang of tentens by now.                                                                               | 📚     |       | HIRAGANA_DA
 30 | です       | です         | To be                               | Desu! Usually contracted and said "des" because it's said so often. It means "is" or "am". "たかい　です" means "It is tall".                          | 👉     |       | HIRAGANA_DA
 31 | どうして   | どうして     | Why?                                | This word means "why?". Just like in English, you put it at the start of a sentence to make it a question.                                             | ❓     |       | HIRAGANA_DA
 32 | 犬         | いぬ         | Dog                                 | This word means "dog". It's actually snuck into English quite unnoticed. You know the Japanese breed, shiba *inu*? 😉"                                  | 🐕     |       | HIRAGANA_NA
 33 | 猫         | ねこ         | Cat                                 | This word is "cat". The first letter is "ne"                                                                                                           | 🐈     |       | HIRAGANA_NA
 34 | 昨日       | きのう       | Yesterday                           | This is "yesterday", and the new letter is "no"                                                                                                        | ⬅️📆   |       | HIRAGANA_NA
 35 | 何         | なに         | What?                               | "Omae wa mou shindeiru." "NANI!?" ...Sorry about that. This word is "what?"                                                                            | ❓     |       | HIRAGANA_NA
 36 | 温泉       | おんせん     | Onsen, Japanese hot spring          | This word doesn't really have an English translation. The closest is "hot spring".                                                                     | ♨     |       | HIRAGANA_N
 37 | 元気       | げんき       | Lively, well                        | This word can mean "good/well" as in "How are you" "げんき　です". It can also mean "lively", like you might describe a festival.                      | 😄     |       | HIRAGANA_N
 38 | 外国人     | がいこくじん | Foreign person, non-Japanese person | If you're not Japanese by blood, you might get referred to as this when you visit Japan.                                                               | 🙋<U+200D>♀️🚢  |       | HIRAGANA_N
 39 | 人         | ひと         | Person                              | This word means "person", and the new letter is "hi". It's not pronounced "hie"!                                                                       | 👩     |       | HIRAGANA_HA
 40 | はい       | はい         | Yes                                 | This word means "yes". The new letter is "は".                                                                                                         | ✅     |       | HIRAGANA_HA
 41 | 豆腐       | とうふ       | Tofu                                | This is a word that's become a part of English: "Tofu". Make sure to read it with the correct pronunciation.                                           | 🍢     |       | HIRAGANA_HA
 42 | 変         | へん         | Strange, weird                      | This means "strange" or "weird". The new letter is "he".                                                                                               | 🤔     |       | HIRAGANA_HA
 43 | 日本       | にほん       | Japan                               | You might know this word already: "nihon". It's the Japanese word for "Japan".                                                                         | 🇯🇵    |       | HIRAGANA_HA
 44 | バカ       | ばか         | Idiot                               | If you watch any anime you'll know this one. It means "idiot".                                                                                         | 🤬     |       | HIRAGANA_BA
 45 | 僕         | ぼく         | I, me (male)                        | This is the pronoun for "I", or "me". It's usually only used by males. You'll learn the female one soon!                                               | 🙋<U+200D>♂️   |       | HIRAGANA_BA
 46 | 人々       | ひとびと     | People, everybody                   | This means "people" or "everyone". Notice how similar it is to "ひと" (person).                                                                        | 👥     |       | HIRAGANA_BA
 47 | 危ない     | あぶない     | Dangerous                           | This means "dangerous". You'll see it on Japanese signs a lot, near train stations.                                                                    | ⚠️    |       | HIRAGANA_BA
 48 | お弁当     | おべんとう   | Bento box, Japanese lunch box       | This is the word for "bento box". In Japanese, it's "obentō". The "O" at the start shows respect.                                                      | 🍱     |       | HIRAGANA_BA
 49 | うまい     | うまい       | Delicious                           | The new character is "ma". This means "delicious". It's a *very* common word!                                                                          | 🤤     |       | HIRAGANA_MA
 50 | すみません | すみません   | Excuse me                           | This means "excuse me". The new character is "mi". It's also one of the most common words!                                                             | 🙇<U+200D>♂️   |       | HIRAGANA_MA
 51 | おすすめ   | おすすめ     | Recommendation                      | The new letter is "me". It means "recommendation", and you'll see it on every menu in Japan.                                                           | 🌟     |       | HIRAGANA_MA
 52 | 寒い       | さむい       | Cold (weather)                      | This means "cold", but only for weather. There's a different word for cold items. The new letter is "mu".                                              | 🥶     |       | HIRAGANA_MA
 53 | もの       | もの         | Thing                               | This means "thing". It can be used to refer to almost any physical object. The new letter is "mo".                                                     | 📦     |       | HIRAGANA_MA
 54 | 私         | わたし       | I, me (female)                      | This means "me", but the female version. Men can use it when they're being formal too.                                                                 | 🙋<U+200D>♀️   |       | HIRAGANA_WA
 55 | 可愛い     | かわいい     | Cute                                | This means "cute". If you're learning Japanese, you'll definitely have seen this word already.                                                         | 🎀     |       | HIRAGANA_WA
 56 | 部屋       | へや         | Room                                | This is "room". The new letter is "ya". Very useful word for booking accomodation.                                                                     | 🏨     |       | HIRAGANA_YA
 57 | 有名       | ゆうめい     | Famous                              | This word means "famous". The new letter is "yu".                                                                                                      | 👨<U+200D>🎤    |       | HIRAGANA_YA
 58 | 強い       | つよい       | Strong                              | This means "strong". The new letter is "yo                                                                                                             | 💪     |       | HIRAGANA_YA
 59 | 写真       | しゃしん     | Photo                               | This is "photo": "shashin". A very useful word for asking strangers to take tourist photos of you.                                                     | 📷     |       | HIRAGANA_LYA
 60 | 今日       | きょう       | Today                               | This means "today" and is written "kyou".                                                                                                              | 📅     |       | HIRAGANA_LYA
 61 | 週         | しゅう       | Week                                | This means "week" and is written as "shuu".                                                                                                            | 🗓     |       | HIRAGANA_LYA
 62 | ちょっと   | ちょっと     | A little bit                        | This means "a little bit" and is written as "chotto". (It's an extremely common word)                                                                  | 👌     |       | HIRAGANA_LYA
 63 | なるほど   | なるほど     | I see!                              | This is a short phrase that means "I see!". The new letter is "ru"                                                                                     | 😲     |       | HIRAGANA_RA
 64 | 柔らかい   | やわらかい   | Soft, tender                        | This means "soft" (for anything) or "tender" (for food). The new letter is "ra".                                                                       | 🧸     |       | HIRAGANA_RA
 65 | 綺麗       | きれい       | Pretty, clean                       | This means "pretty" or "clean". The new letter is "re".                                                                                                | ✨     |       | HIRAGANA_RA
 66 | 鮪         | まぐろ       | Tuna                                | This is the word for "tuna", either the live fish or the raw meat. The new letter is "ro".                                                             | 🍣     |       | HIRAGANA_RA
 67 | ありがとう | ありがとう   | Thanks                              | This means "thanks", but you already knew that! Make sure to learn the real pronunciation.                                                             | 🎁     |       | HIRAGANA_RA
 68 | パチンコ   | ぱちんこ     | Pachinko                            | This is "pachinko", the Japanese gambling game with little metal balls.                                                                                | 🎰     |       | HIRAGANA_PA
 69 | 鉛筆       | えんぴつ     | Pencil                              | This is the Japanese word for "pencil".                                                                                                                | ✏️    |       | HIRAGANA_PA
 70 | 切符       | きっぷ       | Ticket                              | This means "ticket". You might need to know this one if you visit theme parks and similar places.                                                      | 🎟     |       | HIRAGANA_PA
 71 | ペン       | ぺん         | Pen                                 | This is the Japanese word for "pen"... it's the same as in English                                                                                     | 🖋     |       | HIRAGANA_PA
 72 | 散歩       | さんぽ       | A walk, stroll                      | This word means "a walk" or "a stroll".                                                                                                                | 🚶<U+200D>♂️   |       | HIRAGANA_PA
 73 | を         | を           | -                                   | This new character is techinically "wo", but it's usually pronounced as "o". It's a special letter that's not really used in real words.               | ⁉️    |       | HIRAGANA_WA