 id  | character |   type   | readings
-----+-----------+----------+----------
   1 | あ        | HIRAGANA |
   2 | い        | HIRAGANA |
   3 | う        | HIRAGANA |
   4 | え        | HIRAGANA |
   5 | お        | HIRAGANA |
   6 | か        | HIRAGANA |
   7 | き        | HIRAGANA |
   8 | く        | HIRAGANA |
   9 | け        | HIRAGANA |
  10 | こ        | HIRAGANA |
  11 | さ        | HIRAGANA |
  12 | し        | HIRAGANA |
  13 | す        | HIRAGANA |
  14 | せ        | HIRAGANA |
  15 | そ        | HIRAGANA |
  16 | が        | HIRAGANA |
  17 | ぎ        | HIRAGANA |
  18 | ぐ        | HIRAGANA |
  19 | げ        | HIRAGANA |
  20 | ご        | HIRAGANA |
  21 | ざ        | HIRAGANA |
  22 | じ        | HIRAGANA |
  23 | ず        | HIRAGANA |
  24 | ぜ        | HIRAGANA |
  25 | ぞ        | HIRAGANA |
  26 | た        | HIRAGANA |
  27 | ち        | HIRAGANA |
  28 | つ        | HIRAGANA |
  29 | て        | HIRAGANA |
  30 | と        | HIRAGANA |
  31 | だ        | HIRAGANA |
  32 | ぢ        | HIRAGANA |
  33 | づ        | HIRAGANA |
  34 | で        | HIRAGANA |
  35 | ど        | HIRAGANA |
  36 | な        | HIRAGANA |
  37 | に        | HIRAGANA |
  38 | ぬ        | HIRAGANA |
  39 | ね        | HIRAGANA |
  40 | の        | HIRAGANA |
  41 | は        | HIRAGANA |
  42 | ひ        | HIRAGANA |
  43 | ふ        | HIRAGANA |
  44 | へ        | HIRAGANA |
  45 | ほ        | HIRAGANA |
  46 | ば        | HIRAGANA |
  47 | び        | HIRAGANA |
  48 | ぶ        | HIRAGANA |
  49 | べ        | HIRAGANA |
  50 | ぼ        | HIRAGANA |
  51 | ぱ        | HIRAGANA |
  52 | ぴ        | HIRAGANA |
  53 | ぷ        | HIRAGANA |
  54 | ぺ        | HIRAGANA |
  55 | ぽ        | HIRAGANA |
  56 | ま        | HIRAGANA |
    59 | め        | HIRAGANA |
  60 | も        | HIRAGANA |
  61 | や        | HIRAGANA |
  62 | ゆ        | HIRAGANA |
  63 | よ        | HIRAGANA |
  64 | ら        | HIRAGANA |
  65 | り        | HIRAGANA |
  66 | る        | HIRAGANA |
  67 | れ        | HIRAGANA |
  68 | ろ        | HIRAGANA |
  69 | わ        | HIRAGANA |
  70 | を        | HIRAGANA |
  71 | ん        | HIRAGANA |
  72 | きゃ      | HIRAGANA |
  73 | きゅ      | HIRAGANA |
  74 | きょ      | HIRAGANA |
  75 | ぎゃ      | HIRAGANA |
  76 | ぎゅ      | HIRAGANA |
  77 | ぎょ      | HIRAGANA |
  78 | しゃ      | HIRAGANA |
  79 | しゅ      | HIRAGANA |
  80 | しょ      | HIRAGANA |
  81 | じゃ      | HIRAGANA |
  82 | じゅ      | HIRAGANA |
  83 | じょ      | HIRAGANA |
  84 | ちゃ      | HIRAGANA |
  85 | ちゅ      | HIRAGANA |
  86 | ちょ      | HIRAGANA |
  87 | にゃ      | HIRAGANA |
  88 | にゅ      | HIRAGANA |
  89 | にょ      | HIRAGANA |
  90 | ひゃ      | HIRAGANA |
  91 | ひゅ      | HIRAGANA |
  92 | ひょ      | HIRAGANA |
  93 | びゃ      | HIRAGANA |
  94 | びゅ      | HIRAGANA |
  95 | びょ      | HIRAGANA |
  96 | ぴゃ      | HIRAGANA |
  97 | ぴゅ      | HIRAGANA |
  98 | ぴょ      | HIRAGANA |
  99 | みゃ      | HIRAGANA |
 100 | みゅ      | HIRAGANA |
 101 | みょ      | HIRAGANA |
 102 | りゃ      | HIRAGANA |
 103 | りゅ      | HIRAGANA |
 104 | りょ      | HIRAGANA |
 105 | っ        | HIRAGANA |