       id        |              title              |                                                  image                                                  | unlocks_ids  | course_id | skill_level | time_estimate
-----------------+---------------------------------+---------------------------------------------------------------------------------------------------------+--------------+-----------+-------------+---------------
 HIRAGANA_PA     | Hiragana Lesson 9 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-pa/title.png     | NEXT_COURSE  | HIRAGANA  | Beginner    |           420
 HIRAGANA_A      | Hiragana Lesson 1               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-a/title.png      | HIRAGANA_KA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_KA     | Hiragana Lesson 2               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ka/title.png     | HIRAGANA_GA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_GA     | Hiragana Lesson 2 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ga/title.png     | HIRAGANA_SA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_SA     | Hiragana Lesson 3               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-sa/title.png     | HIRAGANA_ZA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_ZA     | Hiragana Lesson 3 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-za/title.png     | HIRAGANA_TA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_TA     | Hiragana Lesson 4               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ta/title.png     | HIRAGANA_DA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_DA     | Hiragana Lesson 4 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-da/title.png     | HIRAGANA_NA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_NA     | Hiragana Lesson 5               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-na/title.png     | HIRAGANA_N   | HIRAGANA  | Beginner    |           420
 HIRAGANA_N      | Hiragana Lesson 5 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-n/title.png      | HIRAGANA_HA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_HA     | Hiragana Lesson 6               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ha/title.png     | HIRAGANA_BA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_BA     | Hiragana Lesson 6 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ba/title.png     | HIRAGANA_MA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_MA     | Hiragana Lesson 7               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ma/title.png     | HIRAGANA_WA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_WA     | Hiragana Lesson 7 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-wa/title.png     | HIRAGANA_YA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_YA     | Hiragana Lesson 8               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ya/title.png     | HIRAGANA_LYA | HIRAGANA  | Beginner    |           420
 HIRAGANA_LYA    | Hiragana Lesson 8 - Bonus Round | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-lya/title.png    | HIRAGANA_RA  | HIRAGANA  | Beginner    |           420
 HIRAGANA_RA     | Hiragana Lesson 9               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/hiragana-ra/title.png     | HIRAGANA_PA  | HIRAGANA  | Beginner    |           420
 KATAKANA_1      | Katakana Lesson 1               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/katakana-1/title.png      | KATAKANA_2   | KATAKANA  | Beginner    |           420
 KATAKANA_2      | Katakana Lesson 2               | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/katakana-2/title.png      | KATAKANA_3   | KATAKANA  | Beginner    |           420
 GMR_PARTICLE_WA | Talking about yourself          | https://res.cloudinary.com/holistic-japanese/image/upload/v1587262008/lessons/gmr-particle-wa/title.png |              | GRAMMAR_1 | Beginner    |           420